### ISSUE TITLE
loading svelte packages from node_modules

### ISSUE THREAD

**Issue by darkship** [mihar-22/svelte-jester#23]
Not every Svelte packages are providing CommonJSmodules needed by Jest.

Examples:
svelte-select: provides es, mjs modules and the svelte component 
svelte-calendar: provides only the svelte component.

Is there something I can do to tell jest that it has to look for the svelte component when it comes from node_modules?
```
import Select from 'svelte-select';
import * as CommonJSSelect from 'svelte-select';
const SelectComponent = Select || CommonJSSelect; // issues with jest, needs CommonJS
```

**Comment by mihar-22** [comment]
Hey @darkship you can use [`jest-svelte-resolver`](https://www.npmjs.com/package/jest-svelte-resolver) to make Jest resolve the `.svelte` files.

**Comment by darkship** [comment]
I tried it. It breaks the handling of my own svelte components with svelte-jester. And I don't find the related github page of this package

**Comment by basarbk** [comment]
Hi @darkship ,
You can use "transformIgnorePatterns" configuration of jest. By default the node_modules folder is ignored. So by setting it as follows
```
  "transformIgnorePatterns": [
    "node_modules/(?!(svelte-select|svelte-calendar)/)"
  ],
```
the folders "svelte-select" and "svelte-calendar" in the node_modules, will be transformed based on the transform config.

**Comment by sebastianrothe** [comment]
This should be fixed with Jest 27+ and Sveltekit requiring ESM.
