### ISSUE TITLE
Use jest async transformers when available

### ISSUE THREAD

**Issue by benmccann** [mihar-22/svelte-jester#25]
This can't be done until facebook/jest#9504 is completed (related PR pending facebook/jest#9889). Filing here to track though

In order support preprocessing this library needs to [spin up a new node instance for each source file](https://github.com/mihar-22/svelte-jester/blob/master/src/transformer.js#L15) which seems like it should have a negative performance impact.

One the jest work is done to support async transformers then we should use those here

**Comment by mihar-22** [comment]
Awesome thanks for setting this up @benmccann!

**Comment by benmccann** [comment]
Support now exists in Jest! However, it hasn't yet been released yet, so we'll need to wait a little in order to be able to use it

**Comment by benmccann** [comment]
It looks like there's a beta version available at `v27.0.0-next.6` that could probably be used to start testing this feature

**Comment by sebastianrothe** [comment]
Jest 27 has just been [released](https://github.com/facebook/jest/blob/master/CHANGELOG.md). Once my PR has been merged, I will give it a try.

**Comment by benmccann** [comment]
I was just curious @sebastianrothe if this is something you're still planning to give a go of?

**Comment by sebastianrothe** [comment]
> I was just curious @sebastianrothe if this is something you're still planning to give a go of?

I'd love to, but my project at work takes up all my time. I'll try to give it a go at the beginning of next month.

**Comment by benmccann** [comment]
Looks like this will probably depend on https://github.com/mihar-22/svelte-jester/issues/55

**Comment by mihar-22** [comment]
Extending on a few things @benmccann noted [here](https://github.com/mihar-22/svelte-jester/pull/56#discussion_r680584216) that I agree with.

If we want to support async transforms and not tie ourselves to Jest versioning, we'll need to support both sync and async transformers for the time being until a reasonable time where we can deprecate sync transformers. We can't force existing codebases using `26.x` to upgrade, and if they decide not to upgrade they'll miss bug fixes or any new features. Thus, we need to support both for now.

I'm not sure what the best way will be to determine if async transforms are supported. Ideas include:

- Node environment variable that indicates current Jest version?
- Extracting Jest version from `pacakge.json`?
- Some kind of support check for async transformer support?

Keep in mind, it may executed inside a monorepo, and note any existing `svelte-jester` CLI flags that may change final transformation.

**Comment by benmccann** [comment]
>  We can't force existing codebases using 26.x to upgrade

I'm not sure it'd be much of an imposition to ask people to upgrade to v27.x. I just took a look at the breaking changes in v27 and they seem quite minor: https://jestjs.io/blog/2021/05/25/jest-27#features-coming-with-breaking-changes

**Comment by mihar-22** [comment]
I'll be honest I didn't actually look at the breaking changes. There seems to be nothing serious, I was thinking of a few other things outside of the noted breaking changes, but again nothing of importance.

If it all seems okay, we can just ignore what I said and next major version of `svelte-jester` can simply transition to async only transformers and bump minimum version for Jest in peer deps to `>=27`.

**Comment by sebastianrothe** [comment]
> Extending on a few things @benmccann noted [here](https://github.com/mihar-22/svelte-jester/pull/56#discussion_r680584216) that I agree with.
> 
> If we want to support async transforms and not tie ourselves to Jest versioning, we'll need to support both sync and async transformers for the time being until a reasonable time where we can deprecate sync transformers. We can't force existing codebases using `26.x` to upgrade, and if they decide not to upgrade they'll miss bug fixes or any new features. Thus, we need to support both for now.
> 
> I'm not sure what the best way will be to determine if async transforms are supported. Ideas include:
> 
>     * Node environment variable that indicates current Jest version?
> 
>     * Extracting Jest version from `pacakge.json`?
> 
>     * Some kind of check for async transformer support?
> 
> 
> Keep in mind, it may executed inside a monorepo, and note any existing `svelte-jester` options that may change final transformation.

From my understanding, we can keep the existing code and just write a new async transformer. I think I already did some steps to extract functionality into seperate files. The only difference will be, how the transformer is called. Either as a subprocess with node or as an async function.

**Comment by benmccann** [comment]
I don't understand why we'd want to keep the existing code. Calling as a subprocess with node is purely worse. We should just always return an async transformer

**Comment by sebastianrothe** [comment]
Well, Jest <27 doesn't understand async transformers. If we rewrite the code, we loose compatibility with Jest 26.x 
It is fine to me, but I just wanted to point that out.

Guess, people who need to run Jest 26.x can always use an older version, right.

**Comment by benmccann** [comment]
Yeah, that's fine. We listed `jest >= 27` as a peer dependency: 

https://github.com/mihar-22/svelte-jester/blob/1052bed4eb2c3c7c1cc6739ee21363de38f4f7c4/package.json#L46

**Comment by gorjan-mishevski** [comment]
It seems this is not quite resolved.
I am getting the following error:
`
  Jest: synchronous transformer node_modules/svelte-jester/src/transformer.js must export a "process" function.
`

 "svelte-jester": "2.0.1"
 "jest": "27.0.6"
 "svelte": "3.41.0"

**Comment by rkennel** [comment]
Yes, I am seeing same error as @gorjan-mishevski.  Same jest config file

svelte-jester@2.0.1
 jest@27.0.6
svelte@3.42.2

**Comment by ritchieanesco** [comment]
+1. Also same config.

svelte-jester@2.0.1
jest@27.1.1
svelte@3.42.5

**Comment by benmccann** [comment]
Please use the latest version: 2.1.2

**Comment by ritchieanesco** [comment]
@benmccann updating to 2.1.2 now gives me
```TypeError: Jest: a transform must export a `process` or `processAsync` function.``` which was raised in this issue https://github.com/mihar-22/svelte-jester/issues/74. Has this issue regressed?

**Comment by rmunn** [comment]
@ritchieanesco #74 was fixed by #75 but that fix hasn't made its way into a released version yet. I don't know why, because 2.1.2 is unusable, so I'd have thought that 2.1.3 would be more urgent. But once 2.1.3 comes out, it will work. I've verified the fix in #75 by cloning the svelte-jester repo and putting `"svelte-jester": "../svelte-jester"` in my package.json, and then I could successfully use `jest.unstable_mockModule` in my Svelte unit tests.

So wait for 2.1.3 to come out and it should work for you.

**Comment by n00pper** [comment]
I had the same problem as @gorjan-mishevski but 2.1.3 is out now for `svelte-jester`. I updated `jest` as well to the currently latest version (27.2.0) and now I get a new error:
```
Cannot find module './preprocess.js'
Require stack:
      node_modules/svelte-jester/dist/transformer.cjs
      node_modules/@jest/transform/node_modules/jest-util/build/requireOrImportModule.js
      node_modules/@jest/transform/node_modules/jest-util/build/index.js
      node_modules/@jest/transform/build/ScriptTransformer.js
      node_modules/@jest/transform/build/index.js
      node_modules/jest-runtime/build/index.js
      node_modules/@jest/core/build/cli/index.js
      node_modules/@jest/core/build/jest.js
      node_modules/jest/node_modules/jest-cli/build/cli/index.js
      node_modules/jest/node_modules/jest-cli/bin/jest.js
      node_modules/jest/bin/jest.js

      at Object.processSync [as process] (node_modules/svelte-jester/dist/transformer.cjs:115:32)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:612:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:758:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:815:19)
```

**Comment by colehpage** [comment]
> 
> 
> I had the same problem as @gorjan-mishevski but 2.1.3 is out now for `svelte-jester`. I updated `jest` as well to the currently latest version (27.2.0) and now I get a new error:
> 
> ```
> Cannot find module './preprocess.js'
> Require stack:
>       node_modules/svelte-jester/dist/transformer.cjs
>       node_modules/@jest/transform/node_modules/jest-util/build/requireOrImportModule.js
>       node_modules/@jest/transform/node_modules/jest-util/build/index.js
>       node_modules/@jest/transform/build/ScriptTransformer.js
>       node_modules/@jest/transform/build/index.js
>       node_modules/jest-runtime/build/index.js
>       node_modules/@jest/core/build/cli/index.js
>       node_modules/@jest/core/build/jest.js
>       node_modules/jest/node_modules/jest-cli/build/cli/index.js
>       node_modules/jest/node_modules/jest-cli/bin/jest.js
>       node_modules/jest/bin/jest.js
> 
>       at Object.processSync [as process] (node_modules/svelte-jester/dist/transformer.cjs:115:32)
>       at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:612:31)
>       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:758:40)
>       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:815:19)
> ```

@n00pper it was left out of the published version but is being addressed 👍 
https://github.com/mihar-22/svelte-jester/issues/81
