### ISSUE TITLE
Use with rollup plugins

### ISSUE THREAD

**Issue by darbymanning** [mihar-22/svelte-jester#30]
This may not be svelte-jester specific so sorry if this isn't relevant, but I am using [@rollup/plugin-alias](https://github.com/rollup/plugins/tree/master/packages/alias) so that I can import files without defining paths relative to the cwd (eg. `import Button from "$components/Button.svelte"`). Is it possible to provide this alias plugin & config to `svelte-jester` so that tests can also resolve these files correctly?

**Comment by sebastianrothe** [comment]
Did you add the module mapping to your Jest config ?

**Comment by benmccann** [comment]
There is work ongoing to support Vite + Jest that may help you: https://github.com/sodatea/vite-jest/issues/15. Rollup plugins are generally compatible with Vite

**Comment by sebastianrothe** [comment]
> Did you add the module mapping to your [Jest config ](https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring)?

See documentation about jest and alias mappings here https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring

If you use Typescript, you need another mapping in your  `tsconfig.json`.

**Comment by darbymanning** [comment]
Cool, I think I just needed to do some proper setup - thanks!
