### ISSUE TITLE
Support svelte.config.cjs file naming

### ISSUE THREAD

**Issue by mhatvan** [mihar-22/svelte-jester#35]
When trying to run unit tests with SvelteKit, `svelte-jester` throws `Could not find svelte.config.js`.

It would be great to have SvelteKit support!

**Comment by forrestjacobs** [comment]
It looks like [Cosmiconfig v7 handles .cjs files](https://github.com/davidtheclark/cosmiconfig/blob/main/CHANGELOG.md#700). I don't think that is the _only_ change necessary, but it would probably remove the _No loader specified for extension ".cjs"_ error that I'm getting when I try this transform config: `transform: { "^.+\\.svelte$": ["svelte-jester", { preprocess: "./svelte.config.cjs" }] }`

**Comment by forrestjacobs** [comment]
Actually, I just tried it and `{ preprocess: "./svelte.config.cjs" }` totally works if svelte-jester uses Cosmiconfig v7! The type of change is [here](https://github.com/forrestjacobs/svelte-jester/commit/7a0350a5902b5b03c83815b27a994fe5f3451e47), but it's literally just updating the dependency version.

The other question is what should `{ preprocess: true }` do -- should it look for "svelte.config.cjs" if "svelte.config.js" doesn't exist? And the same for `{ rootMode: "upward" }` -- should it also search for "svelte.config.cjs" as well as "svelte.config.js"?

**Comment by mihar-22** [comment]
Hey @forrestjacobs thanks for looking into all this! If you can throw a PR my way for this I'm happy to pull it in and release ASAP. The answer to both questions is yes, it should look for both `svelte.config.js` and `svelte.config.cjs`.

**Comment by forrestjacobs** [comment]
@mihar-22 sure thing! Just opened one.

**Comment by mihar-22** [comment]
Released in `1.4.0` thanks to @forrestjacobs! Thanks!
