### ISSUE TITLE
resolving node modules

### ISSUE THREAD

**Issue by mvolkmann** [mihar-22/svelte-jester#4]
I have a Svelte component I'd like to test that uses a lodash function. Here is the import it uses:

```js
  import get from 'lodash/get';
```

The component works fine in a Svelte app. But when I test this component with Jest and svelte-jester, the value of `get` is undefined. It seems the `import` fails when run in a test. Is there some additional configuration I need to make this work?

**Comment by mihar-22** [comment]
Hey @mvolkmann it's undefined because it is a CommonJS module `module.exports = x` and you are importing it as an ES module. If you do `import * as get from 'lodash/get'` it'll work. However you can just use `lodash-es` which exports the Lodash library as ES modules (https://www.npmjs.com/package/lodash-es). 

It was working in your Svelte app because Webpack or Rollup with the correct plugins will resolve the module regardless if it's a CommonJS or ES module. For example that's what [`@rollup/plugin-commonjs`](https://github.com/rollup/plugins/tree/master/packages/commonjs) does (converts CommonJS modules to ES6).

**Comment by mvolkmann** [comment]
Thanks! I'm trying to use lodash-es now. All my `.svelte` files that use the lodash `get` function now contain this import:

```js
  import get from 'lodash-es/get';
```

My app works correctly with this change, but when I run my Jest tests using svelte-jester I get this error when it hits one of those imports:
"SyntaxError: Cannot use import statement outside a module". Do I need some additional configuration in `jest.config.js`? Here is what that file contains currently:

```js
module.exports = {
  bail: false,
  moduleFileExtensions: ['js', 'svelte'],
  transform: {
    '^.+\\.js$': 'babel-jest',
    '^.+\\.svelte$': 'svelte-jester'
  },
  verbose: true
};
```

**Comment by mihar-22** [comment]
Ahhh it's probably because Jest doesn't transform `node_modules` by default. Try adding the following to your Jest configuration

```js
{
  transformIgnorePatterns: [
    'node_modules/(?!(lodash-es)/)'
  ]
}
```

Also try to export your Babel config as `babel.config.js` because of some known issues with `.babelrc` and Jest.

**Comment by mvolkmann** [comment]
That works! But there is one more issue. Some of my components import a local `.json` file. This works when I run the app, but when I run my tests I get `undefined` from this imports. I had to install and configure `@rollup/plugin-json` to get this work in the app. Is there something else I need to do to enable import `.json` files when tests run?

This is my current `jest.config.js` file:

```js
module.exports = {
  bail: false,
  moduleFileExtensions: ['js', 'svelte'],
  transform: {
    '^.+\\.js$': 'babel-jest',
    '^.+\\.svelte$': 'svelte-jester'
  },
  transformIgnorePatterns: ['node_modules/(?!(lodash-es)/)'],
  verbose: true
};
```

This is my `babel.config.js` file:

```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: 'current'
        }
      }
    ]
  ]
};
```

**Comment by mihar-22** [comment]
You can’t import `.json` files using ES6. You could simply manually transform it to a JavaScript object `export default { }` or you could try this out (https://www.npmjs.com/package/babel-plugin-inline-json-import) but make sure it’s only used when testing by checking `process.env.NODE_ENV === ‘test’` in `babel.config.js`.

**Comment by mvolkmann** [comment]
Ah, that works much better. Thanks!
