### ISSUE TITLE
Svelte-kit support

### ISSUE THREAD

**Issue by Drevoed** [mihar-22/svelte-jester#44]
Currently svelte-kit requires ```"type": "module"``` to be present in `package.json`. This does not work with current version of svelte-jester because it uses require under the hood and requires are prohibited with ES modules

**Comment by sebastianrothe** [comment]
Hm, we have type: module in package.json and it works without problems. What is the error you get?

The adapters dont work in the latest next-version. Thats true. We neede to downgrad them to the version before the switch ti ESM.

**Comment by sebastianrothe** [comment]
Might be a duplicate of #6

**Comment by sebastianrothe** [comment]
I'll give it a try, because we need it for our current project as well.

**Comment by geoidesic** [comment]
So... how does one make it work with Sveltekit? I mean what does one import in your test? With standard svelte it would be `import App from '../App.svelte';` what is it for SvelteKit? Could you provide a sample test that works with the default "demo-app" installation of Sveltekit?

**Comment by navneetsharmaui** [comment]
@geoidesic see the tests in the https://github.com/navneetsharmaui/sveltkit-starter
I've not updated the project with latest svelte-jester but it will provide you base for you how to setup your project.

**Comment by geoidesic** [comment]
@navneetsharmaui thx, I checked that out –– couldn't get it to build and also didn't see any tests in there?

**Comment by navneetsharmaui** [comment]
@geoidesic I will be updating the project with latest svelte-jester, as test working previously since the sveltekit moved to esmodule and by that time svelte-jester didn't had the support for the esmodule.

**Comment by navneetsharmaui** [comment]
@geoidesic You can check the project now, I've checked in some changes.
