### ISSUE TITLE
 Unrecognized option 'sourcemap'  when I connect svelte-jester

### ISSUE THREAD

**Issue by MikeProcudin** [mihar-22/svelte-jester#45]
Hi @mihar-22 ,

I am looking into svelte-jester for few days now, and managed to configure it, however, it seems that I am failing on the last bit, and it keeps looking for sourcemap option when I connect svelte-jester to transformer.

```
> jest

 FAIL  tests/Main.test.js
  ● Test suite failed to run

    Unrecognized option 'sourcemap'

      at Object.keys.forEach.key (node_modules/svelte/src/compiler/compile/index.ts:40:10)
          at Array.forEach (<anonymous>)
      at validate_options (node_modules/svelte/src/compiler/compile/index.ts:34:23)
      at Object.compile (node_modules/svelte/src/compiler/compile/index.ts:65:2)
      at Object.process (node_modules/svelte-jester/src/transformer.js:28:25)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:464:35)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:569:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:607:25)

Test Suites: 1 failed, 1 total
```

jest.config.js
```
module.exports = {
	moduleFileExtensions: ['js', 'svelte'],
	testPathIgnorePatterns: ['node_modules'],
	testMatch: ["**/?(*.)+(spec|test).js?(x)"],
	bail: false,
	verbose: true,
	transform: {
		'^.+\\.js$': 'babel-jest',
		'^.+\\.svelte$': ['svelte-jester', {preprocess: false, sourcemap: false,}],

	},
	collectCoverageFrom: [
		"src/*.js",
		"src/*.svelte",
	],
	setupFilesAfterEnv: [
		'@testing-library/jest-dom/extend-expect'
	],
	resolver: 'jest-svelte-resolver',
}
```

babel.config.js
```
module.exports = {
	presets: [
		[
			'@babel/preset-env',
			{
				targets: {
					node: 'current',
				},
			},
		],
	],
	plugins: [
		'@babel/plugin-syntax-dynamic-import',
		[
			'@babel/plugin-transform-runtime',
			{
				useESModules: true
			}
		]
	]
}
```

main.test.js
```
import '@testing-library/jest-dom/extend-expect'
import { render } from '@testing-library/svelte'
import Main from '../src/Main.svelte';


test('The component should exist', () => {
	const { container, getByText } = render(Main, {
		props: {
			a: 'test',
			b: 'test'
		},
	});
	expect(container).toBeTruthy();
});
```

**Comment by MikeProcudin** [comment]
Added preprocessor to the stack, (however, I didn't think that it's need to run a usual (html,css,js) set up. 

```
const sveltePreprocess = require('svelte-preprocess')

module.exports = {
	preprocess: sveltePreprocess(
		{
			defaults: {markup: 'html', script: 'javascript', style: 'css'},
			sourceMap: true,
		}
	)
}
```

now I get here an error 
https://github.com/mihar-22/svelte-jester/blob/1033c4a9c9c3081b590eb5b98c816cc60226c392/src/transformer.js#L17
```
Command failed: node --unhandled-rejections=strict --abort-on-uncaught-exception "C:\Projects\**\node_modules\svelte-jester\src\preprocess.js"
    node: bad option: --unhandled-rejections=strict
```

**Comment by thecodewarrior** [comment]
For the record, I had this same error and it was solved by updating jest, ts-jest, and babel-jest to the latest version. Looking back at when I first installed svelte-jester, it did warn me about the version mismatch, but storybook has been spamming dependency errors, so I didn't notice it.

![Screen Shot 2022-06-05 at 2 47 55 PM](https://user-images.githubusercontent.com/5467669/172072002-41392930-7c99-480a-8659-242def24e6d9.png)

**Comment by sebastianrothe** [comment]
> For the record, I had this same error and it was solved by updating jest, ts-jest, and babel-jest to the latest version. Looking back at when I first installed svelte-jester, it did warn me about the version mismatch, but storybook has been spamming dependency errors, so I didn't notice it.
> 
> ![Screen Shot 2022-06-05 at 2 47 55 PM](https://user-images.githubusercontent.com/5467669/172072002-41392930-7c99-480a-8659-242def24e6d9.png)

Hm, there seem to be different ways to enforce peerDependencies.
