### ISSUE TITLE
Preprocessor errors are hidden

### ISSUE THREAD

**Issue by angryziber** [mihar-22/svelte-jester#5]
Why call preprocessor in a separate process?
If it fails, the standard error remains invisible, stdout returns an empty string and svelte compiler produces an empty component, which just doesn't work and very hard to understand why

**Comment by angryziber** [comment]
I see that most likely subprocess is used for a hacked 'deasync' of svelte.preprocess() call...
Isn't there a better way supported by jest?

Anyway, I would suggest adding '--unhandled-rejections=strict' to child node.

And FYI: the problem I was debugging ended up being a problem with node installed with snap package in Ubuntu: https://github.com/nodejs/node/issues/33456

So this approach can have undesired side-problems that are really hard to debug...

**Comment by mihar-22** [comment]
Hey @angryziber, ye I know it's a shitty hack to make it work but async transformations are currently not supported by Jest. When I was building this transformer I tried a bunch of different approaches but they all had some cost, and this was the most stable work around I could get going. 

The good news is that async transformations are being worked on now (https://github.com/facebook/jest/pull/9889) but seems to be still a little early to tell when it'll be done. 

Thanks for the suggestion on `--unhandled-rejections=strict`, I'll add it in.

**Comment by mihar-22** [comment]
Okay done it's released in `1.0.6`, and I'll immediately switch over to async transforms once they're ready.

**Comment by angryziber** [comment]
@mihar-22 thanks

**Comment by mikebridge** [comment]
I was getting the error `node: bad option: --unhandled-rejections=strict`, so I'll note it here in case anyone is googling that message.  

Node 10.16.3 is still pretty widespread---this flag was only [introduced recently in 10.17.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#2019-10-22-version-10170-dubnium-lts-bethgriggs).
