### ISSUE TITLE
Provide a sample test that works with the default "demo-app" installation of Sveltekit

### ISSUE THREAD

**Issue by geoidesic** [mihar-22/svelte-jester#51]
Could ya? Would ya?

With standard svelte it would be something like:
```
import { render } from "@testing-library/svelte";
import App from "../App.svelte";

test("should render", () => {
  const results = render(App, { props: { name: "world" } });

  expect(() => results.getByText("Hello world!")).not.toThrow();
});
```

But for SvelteKit, there's no `App.svelte` file, and the entrypoints are in the routes folder, so I tried something like this:
```
import { render } from '@testing-library/svelte';
import App from '../routes/index.svelte';

test('should render', () => {
  const results = render(App, { props: { name: 'world' } });
  console.log('results', results);
  expect(() => results.getByText('Hello world!')).not.toThrow();
});
```

But that gives errors like this:
```
    Cannot find module '$lib/Counter/index.svelte' from 'src/routes/index.svelte'
```

So how does one do it?

**Comment by sebastianrothe** [comment]
There is nothing Sveltekit specific. Sveltekit is just the replacement for Sapper. It brings support for Serverside-rendering and PWA.

Do you have a `[moduleNameMapper](https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring)` for `$lib` in your jest config ?

**Comment by benmccann** [comment]
That's basically what https://github.com/rossyman/svelte-add-jest is for
