### ISSUE TITLE
Are there plans to support jest ^27?

### ISSUE THREAD

**Issue by jdkdev** [mihar-22/svelte-jester#55]
Hi, I am having some peer dependency issues and looks like I need jest@27 but svelte-jester only currently supports <=26.

Are there plans to bump that up anytime soon?

Thanks in advance for the hard work on the package!

Best,
Jordan

**Comment by sebastianrothe** [comment]
Once I find some time in my current project :)

**Comment by benmccann** [comment]
Closed in https://github.com/mihar-22/svelte-jester/pull/56
