### ISSUE TITLE
Regression between 1.8.2 and 2.0.0

### ISSUE THREAD

**Issue by bhvngt** [mihar-22/svelte-jester#59]
When I upgrade to `2.0.0`, I get following error
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/sandbox/node_modules/svelte-je
ster/src/svelteconfig' imported from /sandbox/node_modules/svelte-jester/src/transformer.js
```
Here's the [sandbox](https://codesandbox.io/s/dreamy-water-bcnmd?file=/tests/button.test.ts:0-105) where this error can be seen.

If I revert `svelte-jester` to `1.8.2`, sandbox gives a different error but the same code works fine in my local system.

**Comment by sebastianrothe** [comment]
I have the same issue. Working on a fix.

**Comment by winfr34k** [comment]
Hmm there still seems to be a bit of a problem. In our project, we still get stuff like this:

```
Jest: synchronous transformer .../node_modules/svelte-jester/src/transformer.js must export a "process" function.
```

Is this related or a separate issue?

**Comment by bhvngt** [comment]
@winfr34k you may want to refer to messages in this [PR](https://github.com/mihar-22/svelte-jester/pull/60). You can also checkout this [sandbox](https://codesandbox.io/s/dreamy-water-bcnmd?file=/package.json:392-661) where its working as an ESM module in its glory with all kind of configurations :-)

**Comment by winfr34k** [comment]
Thank you, @bhvngt!
However, we seem to still have incompatible dependencies (`jest-mock-extended`), so we can't switch just yet...

If anyone is interested in a diff to what's changed in our svelte/kit project, have a look here: https://github.com/communityvi/communityvi/pull/126/files

**Comment by sebastianrothe** [comment]
> Hmm there still seems to be a bit of a problem. In our project, we still get stuff like this:
> 
> ```
> Jest: synchronous transformer .../node_modules/svelte-jester/src/transformer.js must export a "process" function.
> ```
> 
> Is this related or a separate issue?

You will get this error, if Jest thinks something does not use ESM. Could be Typescript or another transformer.
