### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] - Sapper

### ISSUE THREAD

**Issue by ko-pp** [mihar-22/svelte-jester#86]
Hello,

While this might be a duplicate of #72, I prefer to open a new issue as I'm using Sapper instead of SvelteKit, my apologies if it was not the way to go.

Example of traceback (one for each .svelte file)
```
Failed to collect coverage from <snip>/svelte-jester-bug/src/components/Nav.svelte
ERROR: The "id" argument must be of type string. Received an instance of URL
STACK: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received an instance of URL
    at validateString (internal/validators.js:124:11)
    at Module.require (internal/modules/cjs/loader.js:954:3)
    at require (internal/modules/cjs/helpers.js:92:18)
    at <snip>/svelte-jester-bug/node_modules/svelte-jester/dist/transformer.cjs:79:118
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

How to reproduce:
- Degit Sapper `npx degit "sveltejs/sapper-template#rollup" my-app`
- Setup Jest with svelte-jester and a simple test; at this point, `npx jest` should work
- Add svelte-preprocess, postcss and autoprefixer, change svelte-jester config to use preprocess; `npx jest` will show errors and fail to add svelte files to the coverage

Or simply clone https://github.com/ko-pp/svelte-jester-bug, run `npm i` then `npx jest`

Additional notes:
- I'm using Linux
- while the dependencies are outdated on this repo (Svelte 3.17.3 for instance; I wanted to stay as close as possible to the template to reduce chances of me doing something wrong), I have the same problem on my real project with everything up to date

**Comment by mihar-22** [comment]
Should be fixed now 😄  Let us know if you run into any issues.
