### ISSUE TITLE
Unable to compile Svelte components written in TypeScript

### ISSUE THREAD

**Issue by SeanThompsonUptick** [mihar-22/svelte-jester#9]
This is an issue for unit testing svelte components written in Typescript which now bundles with Svelte.

The svelte-jester compiler works great otherwise but ideally if this could understand TS written components it would make unit testing much easier.

**Comment by SeanThompsonUptick** [comment]
Output of terminal log trying to run tests using svelte testing library with svelte-jester
```
    ParseError: Unexpected token

      at error (node_modules/svelte/src/compiler/utils/error.ts:25:16)
      at Parser$1.error (node_modules/svelte/src/compiler/parse/index.ts:93:3)
      at Parser$1.acorn_error (node_modules/svelte/src/compiler/parse/index.ts:86:8)
      at Object.read_script [as read] (node_modules/svelte/src/compiler/parse/read/script.ts:49:10)
      at tag (node_modules/svelte/src/compiler/parse/state/tag.ts:190:27)
      at new Parser$1 (node_modules/svelte/src/compiler/parse/index.ts:45:12)
      at parse (node_modules/svelte/src/compiler/parse/index.ts:208:17)
      at Object.compile (node_modules/svelte/src/compiler/compile/index.ts:79:14)
      at Object.process (node_modules/svelte-jester/src/transformer.js:18:25)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:463:35)
```

**Comment by mihar-22** [comment]
Doesn't passing in the [typescript preprocessor](https://github.com/sveltejs/svelte-preprocess/blob/master/docs/preprocessing.md#typescript) via `svelte.config.js` and [turning preprocessing on](https://github.com/mihar-22/svelte-jester#preprocess) do the job?

**Comment by SeanThompsonUptick** [comment]
Hi thanks for your response.  I've turned on preprocessing but I'm not sure what you mean by passing in the typescript preprocessor via the svelte.config.js file.  Can you show me what the svelte config file should look like to achieve this please?

**Comment by SeanThompsonUptick** [comment]
Hi, sorry for your trouble here.  I managed to figure it out - your suggestion worked and I thank you for taking the time to help.

**svelte.config.js**
```
const sveltePreprocess = require('svelte-preprocess');

module.exports = {
    preprocess: sveltePreprocess({
        // ...svelte-preprocess options (optional)
    }),
}
```

I guess it wasn't super clear to me how to achieve this so I spent a little time digging around.  Perhaps as a suggestion now that TS is bundled with Svelte we could have a note in the docs alerting devs to do this so they can quickly get their unit tests running.

Thanks again please feel free to close the issue :)

**Comment by camjackson** [comment]
Thanks @SeanThompsonUptick for raising this issue, and @mihar-22 for helping with the solution! I had exactly the same problem.

Perhaps this should be added to the docs for svelte-testing-library? Would a PR for that be helpful?

**Comment by mihar-22** [comment]
That'd be awesome @camjackson :) Something like:

## Typescript

To enable TypeScript support you'll need to setup [svelte-preprocess](https://github.com/sveltejs/svelte-preprocess). 

1. Install `typescript` and `svelte-preprocess`:

```bash
$: npm install typescript svelte-preprocess -D
```

2. Setup `svelte.config.js` at the root of your project:

```js
const sveltePreprocess = require('svelte-preprocess');

module.exports = {
  preprocess: sveltePreprocess({
    // ...
  })
}
```

If you'd like to learn what options you can pass to `sveltePreprocess` then please refer to the [documentation](https://github.com/sveltejs/svelte-preprocess/blob/master/docs/preprocessing.md#typescript).

**Comment by SeanThompsonUptick** [comment]
I think this is a good idea.  Just to add to this, if you choose to use any .ts files in your project, then you might also need `ts-jest` to help you.  I personally was using some .ts files to declare some interfaces and enums that I imported into my svelte components.

In order for your unit tests to run properly these also need to be compiled.  This ended up being my jest configuration in my `package.json` to get this all working smoothly:

```
{
"jest": {
    "transform": {
      "^.+\\.svelte$": [
        "svelte-jester",
        {
          "preprocess": true
        }
      ],
      "^.+\\.js$": "babel-jest",
      "^.+\\.ts$": "ts-jest"
    },
    "moduleFileExtensions": [
      "js",
      "svelte",
      "ts"
    ],
    "setupFilesAfterEnv": [
      "@testing-library/jest-dom/extend-expect"
    ]
  }
}
```

Thanks to you both for your contributions.

**Comment by camjackson** [comment]
Thanks @SeanThompsonUptick, good catch. From my own experimenting, it seems that if I have ts-jest set up then I don't need babel-jest as well, _as long as all my code is in .ts files_. I think it will support .js files as well if configured that way too: https://kulshekhar.github.io/ts-jest/user/config/#the-3-presets.

That's assuming of course that babel was only being used for es module transpilation, which is all I was using it for. If people are using other babel transforms then they would need both babel-jest and ts-jest, and they'd need to be set up to play nicely with each other.

Will have a PR open shortly.
